# java version
language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"


# Jar 파일을 S3에 업로드
before_deploy:
  - echo "Preparing for deploy"
  - zip -r centerthon ./*
  - mkdir -p deploy
  - mv centerthon.zip deploy/centerthon.zip

deploy:
  - # S3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: s3-centerthon
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true
    on:
      branch: main
    script:
      - echo "S3 deployment completed"

  # codeDeploy
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: s3-centerthon # S3 버킷
    key: centerthon.zip # build 파일 압축 전달
    bundle_type: zip
    application: centerthon # codedeploy 애플리케이션
    deployment_group: centerthon-group # codedeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed : true
    on:
      branch: main
    script:
      - echo "CodeDeploy deployment completed"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - mj020503@naver.com