name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: joominse0/centerthon-be
          stage: main
          yaml: |
            name: centerthon-be
            app: java@17
            options:
              ports: 8080
              env:
                - name: CHATGPT_KEY
                  secret: CHATGPT_KEY
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: DB_URL
                  secret: DB_URL
                - name: DB_USERNAME
                  secret: DB_USERNAME
                - name: STT_ID
                  secret: STT_ID
                - name: STT_SECRET
                  secret: STT_SECRET
                - name: STT_URL
                  secret: STT_URL
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
